### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by rhonyabdullah** [MedanLinux/SitusWebMedanLinux#1]
@adipginting bg bisa tolong di update file readme-nya yang berisi IDE apa yang di pake, dll, sama pic. KPLI yang kemarin di post di taruh di readme, jadi bisa jelas kalau ada orang lain yang baca 👍

**Comment by adipginting** [comment]
Pic yang berisi daftar sosial media?

**Comment by rhonyabdullah** [comment]
betul bg @adipginting soalnya kita juga butuh massa yang aktif, siapa tau ada yg berminat buat ikut selama pengembangan web.
